services:
  web:
    build:
      context: ./app  #build locally from a docker file in the app directory
      dockerfile: Dockerfile
      args:
        VERSION: "1.0"
    image: myapp:1.0
    ports:
      - "5000:5000"
    environment:
      - API_URL=http://api:8000
      - app_name=Hitesh
    volumes:
      - .:/app
    depends_on:
      - api
    networks:
      - mynetwork
  api:
    build:
      context: .
      dockerfile: Dockerfile_Module2
    networks:
      - mynetwork
    image: myapi:1.0
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api  #bind mount

volumes:
  app:

networks:
  mynetwork:

