# Dockerfile_Module2 - Advanced example with main.py
FROM python:3.12-slim

WORKDIR /apps

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

ENTRYPOINT ["python3", "main.py"]